SELECT ?item WITH {
  SELECT (?item AS ?item_) WHERE {
    ?item wdt:P31 wd:Q5;
          wikibase:sitelinks ?sitelinks. hint:Prior hint:rangeSafe true.
    ?item wikibase:statements ?statements. hint:Prior hint:rangeSafe true.
    FILTER(?sitelinks > 75)
    FILTER(?statements < 50)
  }
  ORDER BY ASC(?statements)
  LIMIT 50
} AS %results WHERE {
  {
    INCLUDE %results.
    BIND(?item_ AS ?item)
  } UNION {
    INCLUDE %results.
    ?property wikibase:propertyType wikibase:WikibaseItem;
              wikibase:directClaim ?wdt.
    ?item_ ?wdt ?item.
  }
}
